theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "multiple"
true-color = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]
