[[language]]
name = "go"
rulers = [120]

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "python"
language-servers = [ "pyright", "pylsp" ]
formatter = { command = "black", args = ["-"] }
auto-format = true
rulers = [80, 88]

[language-server.gopls.config]
buildFlags = ["-tags=integration"]

[language-server.vscode-json-language-server]
command = "vscode-json-languageserver"

[[language]]
name = "elixir"
auto-format = true

# [language-server.rust-analyzer.config.procMacro.ignored]
# leptos_macro = [
#     # Optional:
#     "component",
#     "server"
# ]

# [language-server.rust-analyzer.config.cargo]
# features = ["ssr"]

# [language-server.rust-analyzer.config.check]
# features = ["ssr"]
